// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqS0P6bUQIHHOBJiaUR7wZySucGUomJ-k',
    appId: '1:506244676211:web:b915ab453bd9b28b840806',
    messagingSenderId: '506244676211',
    projectId: 'uptask-4768f',
    authDomain: 'uptask-4768f.firebaseapp.com',
    storageBucket: 'uptask-4768f.firebasestorage.app',
    measurementId: 'G-3VM73Q9S5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhk8NiMyUQp_zyCVcpIlUINu67YulAvI',
    appId: '1:506244676211:android:a86eeb6f5893ae12840806',
    messagingSenderId: '506244676211',
    projectId: 'uptask-4768f',
    storageBucket: 'uptask-4768f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVW6ZRumx8zknhkySgUw6GUlC9TirCvk',
    appId: '1:506244676211:ios:6d52289ff311fd1a840806',
    messagingSenderId: '506244676211',
    projectId: 'uptask-4768f',
    storageBucket: 'uptask-4768f.firebasestorage.app',
    iosBundleId: 'com.example.uptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEVW6ZRumx8zknhkySgUw6GUlC9TirCvk',
    appId: '1:506244676211:ios:6d52289ff311fd1a840806',
    messagingSenderId: '506244676211',
    projectId: 'uptask-4768f',
    storageBucket: 'uptask-4768f.firebasestorage.app',
    iosBundleId: 'com.example.uptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqS0P6bUQIHHOBJiaUR7wZySucGUomJ-k',
    appId: '1:506244676211:web:bd6fc7e49d41667e840806',
    messagingSenderId: '506244676211',
    projectId: 'uptask-4768f',
    authDomain: 'uptask-4768f.firebaseapp.com',
    storageBucket: 'uptask-4768f.firebasestorage.app',
    measurementId: 'G-KHHN743VDC',
  );

}